apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-friends-server
  labels:
    app: minecraft
    instance: mc-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
        instance: mc-2
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8s-cp2
      containers:
      - name: minecraft
        image: itzg/minecraft-server:java21
        env:
        - name: TZ
          value: "America/Costa_Rica"
        - name: EULA
          value: "TRUE"
        - name: MEMORY
          value: "8G"
        - name: TYPE
          value: "FABRIC"
        - name: VERSION 
          value: "1.21.1"
        - name: ENABLE_COMMAND_BLOCK
          value: "true"  
        ports:
        - containerPort: 25565
          name: minecraft
        volumeMounts:
        - mountPath: /data
          name: mc-storage

      - name: minecraft-exporter
        image: sevargas07/minecraft-exporter:0.1.0
        env:
        - name: TZ
          value: "America/Costa_Rica"
        - name: RCON_HOST
          value: "127.0.0.5"
        - name: RCON_PORT
          value: "25575"
        - name: RCON_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mc-rcon
              key: password
        - name: EXPORTER_PORT
          value: "8000"
        - name: INTERVAL_SECONDS
          value: "10" 
        ports:
        - containerPort: 8000
          name: metrics

      volumes:
      - name: mc-storage
        persistentVolumeClaim:
          claimName: minecraft-pvc-friends
