apiVersion: v1
kind: Service
metadata:
  name: minecraft-friends-lb
  annotations:
    metallb.io/address-pool: services-pool
spec:
  type: LoadBalancer
  loadBalancerIP: 172.20.50.120
  selector:
    app: minecraft
    instance: mc-2
  ports:
    - name: minecraft
      protocol: TCP
      port: 25565
      targetPort: 25565
  
