apiVersion: v1
kind: Service
metadata:
  name: minecraft-lb
  annotations:
    metallb.io/address-pool: services-pool
spec:
  type: LoadBalancer
  LoadBalancerIP: 172.20.50.110
  selector:
    app: minecraft
  ports:
    - name: minecraft
      protocol: TCP
      port: 25565
      targetPort: 25565
  
