apiVersion: v1
kind: Service
metadata:
  name: minecraft-lb
spec:
  selector:
    app: minecraft
  ports:
    - protocol: TCP
      name: minecraft
      port: 25565
      targetPort: 25565
  type: LoadBalancer
  LoadBalancerIP: 172.20.50.10 
